### ISSUE TITLE
evohome_cc 0.9.9 is incompatible with HA 0.89 

### ISSUE THREAD

**Issue by furiaceka87** [zxdavb/evohome#33]
**Home Assistant release**: 0.89

**evohome_cc version:**

> {
>     "evohome_cc": {
>         "version":         "0.9.9",
>         "local_location":  "custom_components/evohome_cc/__init__.py",
>         "remote_location": "https://raw.githubusercontent.com/zxdavb/evohome/v0.9.8/evohome_cc/__init__.py",
>         "visit_repo":      "https://github.com/zxdavb/evohome"
>     },
>     "climate.evohome_cc": {
>         "version":         "0.9.8",
>         "local_location":  "custom_components/evohome_cc/climate.py",
>         "remote_location": "https://raw.githubusercontent.com/zxdavb/evohome/v0.9.8/evohome_cc/climate.py",
>         "visit_repo":      "https://github.com/zxdavb/evohome"
>     },
>     "water_heater.evohome_cc": {
>         "version":         "0.9.8",
>         "local_location":  "custom_components/evohome_cc/water_heater.py",
>         "remote_location": "https://raw.githubusercontent.com/zxdavb/evohome/v0.9.8/evohome_cc/water_heater.py",
>         "visit_repo":      "https://github.com/zxdavb/evohome"
>     }
> }

**LOG of the error:**

> 2019-03-07 13:49:26 WARNING (MainThread) [homeassistant.loader] You are using a custom component for evohome_cc which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
> 2019-03-07 13:49:26 WARNING (MainThread) [homeassistant.loader] You are using a custom component for custom_updater which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
> 2019-03-07 13:49:37 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.evohome_cc.climate. Make sure all dependencies are installed
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/site-packages/homeassistant/loader.py", line 166, in _load_file
>     module = importlib.import_module(path)
>   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "/config/custom_components/evohome_cc/climate.py", line 18, in <module>
>     from homeassistant.components.climate import (
> ImportError: cannot import name 'SUPPORT_TARGET_TEMPERATURE' from 'homeassistant.components.climate' (/usr/local/lib/python3.7/site-packages/homeassistant/components/climate/__init__.py)
> 2019-03-07 13:49:37 ERROR (MainThread) [homeassistant.loader] Unable to find platform evohome_cc. Search path was limited to path of component: custom_components
> 2019-03-07 13:49:37 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform evohome_cc.climate: Platform not found.

**Comment by zxdavb** [comment]
This is due to a change in HA 0.89, the component _will_ work in 0.88. it will _not_ work in 0.89.

I have a tested fix for this, but the fix will break 0.88.

**Comment by furiaceka87** [comment]
Ok I will wait for the fix.

**Comment by zxdavb** [comment]
Yes, stay on 0.88 until then.

**Comment by jarrah31** [comment]
I am also happy to test a fix on 0.89 as there's a bug fix on this version that I need so was hoping to upgrade this evening, but happy to wait for now.

**Comment by zxdavb** [comment]
@jarrah31 @furiaceka87 See: https://community.home-assistant.io/t/refactored-honeywell-evohome-custom-component-eu-only/59733/321
